version: "3.7"
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shushi@2019
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./mysql_data:/var/lib/mysql
#      - ./areacode.sql:/usr/local/areacode.sql
